apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tfrun-orchestrator-sample
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: orchestrator-api-demo
  path: ./fluxcd/apps/tfrun-orchestrator/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
