apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-lab-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.50.10.100-10.50.10.103

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-lab-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-lab-pool