---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: whoami-gateway
  namespace: traefik-whoami
spec:
  gatewayClassName: traefik
  listeners:
    - name: whoami-http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-http
  namespace: traefik-whoami
spec:
  parentRefs:
    - name: whoami-gateway
      sectionName: whoami-http
  hostnames:
    - whoami.yuxep.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: whoami
          port: 80