---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: whoami-gateway
  namespace: traefik-whoami
spec:
  gatewayClassName: traefik
  listeners:
  - protocol: HTTP
    port: 80
    name: whomai-http
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-http
  namespace: traefik-whoami
spec:
  parentRefs:
    - name: whoami-gateway
      sectionName: http
      kind: Gateway

  hostnames:
    - whoami.yuxep.com

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: whoami
          namespace: traefik-whoami
          port: 80