apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-store
  namespace: flux-system
spec:
  interval: 3m
  path: ./fluxcd/apps/overlays/home-lab/demo-store
  prune: true
  targetNamespace: demo-store
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
      namespace: flux-system